
POST http://localhost:5000/users/register HTTP/1.1
content-type: application/json

{
    "firstName":"eyal",
    "lastName":"delarea",
    "email":"eyaldelarea@gmail.com",
    "password1":"delarea6",
    "password2":"delarea6"
}

###

GET http://localhost:5000/dashboard

###

DELETE http://localhost:5000/employees/:611d1ac5ec72de1a80fe4aa0

###

PUT http://localhost:5000/employees/:611d1d59a35faf21c6981cfe
content-type: application/json

{
    "name":"odldNsame",
    "id":"611d1d59a35faf21c6981cfe"
    
}

###

POST http://localhost:5000/users/login HTTP/1.1
content-type: application/json

{
    "email":"eyaldelarea@gmail.com",
    "password":"delarea6"
}


